GenericExecuteSynth "echo \'$DATA\' | /home/fahmida/.local/share/com.mikeasoft.pied/piper/piper --model /home/fahmida/.local/share/com.mikeasoft.pied/models/en_us-kusal-medium.onnx --output_raw | $PLAY_COMMAND --raw --channels 1 --rate 22050"
AddVoice "en_us" "MALE1" "Piper"
