[General]
key_pmi=4374132187
key_pmi_invite_msg="Tasnuva Fahmida is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Tasnuva Fahmida's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://us04web.zoom.us/j/4374132187?pwd=eUg1b0Y3OVh3MkpkdllCR2Jya3dkQT09\r\n\r\nMeeting ID: 437 413 2187\r\nPasscode: N3PFW0\r\n\r\n"
