#[[language]]
#name = "markdown"
#language-server = { command = "/home/fahmida/.local/share/cargo/bin/mdpls" }

# config = { markdown.preview.auto = true, markdown.preview.browser = "google-chrome-stable" }
# language-servers = [ "marksman" ]
# language-server = { command = "/usr/bin/marksman" }

[[language]]
name = "rust"

[language-server.rust-analyzer.config]
[language-server.rust-analyzer.config.cargo.buildScripts]
enable = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.procMacro]
enable = true
