#!/bin/bash

mounter &
sleep 1
xdotool key super+1 &
sleep 1
xdotool key super+w &
sleep 5

# xdotool key super+2 &
sleep 1
st -e bash -c "calcurse" &
sleep 1
st -e bash -c "mpv '/mnt/3/Courses/media/audiobooks/Business/Steve Jobs By Walter Isaacson/new/output2.mp3'" &
sleep 1 
st -e bash -c "mpv '/mnt/3/Courses/media/audiobooks/Computer Programming/Devops/1.The-Phoenix-Project/The Phoenix Project.m4b'" &

xdotool key super+2 &
st -e bash -c "calibre" &
sleep 1
st -e bash -c "lf '/home/fahmida/downloads/videos/CoursesTutorials'" &
sleep 1
st -e bash -c "lf '/mnt/3/Courses/media/audiobooks'" &
sleep 1
st -e bash -c "lf '/mnt/3/Courses'" &
sleep 1
xdotool key super+i &
sleep 1
xdotool key super+1 &
