#!/bin/bash

xdotool key super+1 &
sleep 1
mounter &
sleep 1
st -e bash -c "python3 ~/'gits(all-code)'/clock/app3.py" &
sleep 1
st -e bash -c "calcurse" &
sleep 1
xdotool key super+U &
sleep 1

xdotool key super+2 &
sleep 3
# st -- bash -c 'echo "Running CLI Tool 1"; v go-to.txt' &
st -e bash -c "calibre" &
sleep 3
st -e bash -c "lf /home/fahmida/gits(all-code)/rust/hello_world/src" &
sleep 6
xdotool key g+e &

sleep 1 
xdotool key super+3 &
sleep 1
st -e bash -c "lf /mnt/3/Courses/media/audiobooks/Computers/devops-From-Start-To-Finshed" &
sleep 3

xdotool key super+4 &
sleep 1
st -e bash -c "lf ~/'gits(all-code)'/rust/small-exercises/rustlings/exercises/options" &
sleep 3
st -e bash -c "lf /home/fahmida/downloads/videos/CoursesTutorials/Rust/learning" &
sleep 3

xdotool key super+2 &
sleep 2
