#!/bin/bash

################################################## For learning more: https://timeapi.io/swagger/index.html ##################################################

sudo date -s "20 jan 2024 3:00 pm";

API_URL="https://timeapi.io/api/Time/current/zone?timeZone=Asia/Dhaka"

response=$(curl -s "$API_URL")

if [ -z "$response" ]; then
  echo "Error: Failed to fetch data from the API."
  exit 1
fi

# Parse the response using jq (make sure jq is installed)
numaric_date=$(echo "$response" | jq '.date')
day=$(echo "$response" | jq '.day')
month=$(echo "$response" | jq '.month')
year=$(echo "$response" | jq '.year')
time_24=$(echo "$response" | jq '.time')
time_zone=$(echo "$response" | jq '.timeZone')
name_of_week=$(echo "$response" | jq '.dayOfWeek')

# echo $(( $(date +%u --date="Wednesday") % 7 + 1 ))
day_of_week=$(echo $(( $(date +%u --date=${name_of_week//\"/}) % 7 + 1 ))) # number
letter_date=$(date -d $year-$month-$day '+%b %-d') # month name day num
day_of_the_year=$(date -d $year-$month-$day '+%j') # number
time=$(date -d "$year-$month-$day ${time_24//\"/}" +"%I:%M %p") # 24h to 12h

sudo date -s "$year-$month-$day $time"

# echo "'---------+---------+---------+---------+---------+---------+---------'"
# echo "Time Zone: $time_zone"
# echo "Day: $day ($day_of_week)"
# echo "Year: $year"
# echo "Name: ${name_of_week//\"/}"
# echo "Today: $letter_date"
# echo "Month of The Year: $month"
# echo "Day Of The Year: $day_of_the_year days past"
# echo "Day Of The Week: ${day_of_week}th"
# echo "Time: $time"
# echo "'---------+---------+---------+---------+---------+---------+---------'"


echo "'---------+---------+---------+---------+---------+---------+---------'"
echo "Time Zone: $time_zone"
echo "Time: $time"
echo "Day Of The Week: ${day_of_week}th"
echo "Day Of The Year: $day_of_the_year days past"
echo "Month of The Year: $month"
echo "Today: $letter_date"
echo "Name: ${name_of_week//\"/}"
echo "Year: $year"
echo "Day: $day ($day_of_week)"
echo "'---------+---------+---------+---------+---------+---------+---------'"

